Programmatic Transaction Management


NO SE VIO NADA, A MI PARECER ESTA DEPRECADO , PUES UTILIZA DIRECTAMENTE SENTENCIAS SQL , VER DESPUES SI SE USA , LO INTERESANTE ES QUE USA DAO  ( data access object )